---

- name: Generate inmemory inventory
  block:

    - name: Fetch Instance Info
      os_server_info:
        region_name: "{{ openstack_region | default('regionOne') }}"
      register: r_instances

    - name: Add host(s) to inventory
      add_host:
        name: "{{ __instance.private_v4 }}"
        group: 
          - "{{ __instance.metadata.AnsibleGroup }}"
      loop: "{{ r_instances.openstack_servers }}"
      loop_control:
        loop_var: __instance


    - name: Output the in-memory inventory
      block:

      - name: Print hosts to STDOUT
        debug:
          msg:
            - "name: {{ __instance.private_v4 }}"
            - "group: {{ __instance.metadata.AnsibleGroup }}"
        loop: "{{ r_instances.openstack_servers }}"
        loop_control:
          loop_var: __instance
      
      - name: Set AnsibleGroup value
        set_fact:
          AnsibleGroup: "{{ __instance.metadata.AnsibleGroup }}" 
        loop: "{{ r_instances.openstack_servers }}"
        loop_control:
          loop_var: __instance

    - name: DNS pod record update
      # become: true
      when: dns_record_update | default(true) | bool
      block:

        - name: Copy dns records
          template:
            src: templates/example.com.zone.j2
            dest: "{{ dns_zone_file | default('/opt/podman/volumes/bind9-volume/var/named/example.com.zone') }}"

        - name: restart_dns_pod
          command: podman restart bind9

      
  tags:
    - openstack-inventory
    - must
